---
- name: Docker Certs enable
  hosts: "{{ my_hosts | d([]) }}"
  become: true
  gather_facts: true

  vars:
    certs_path: /root/docker-certs

  tasks:
    - name: Check if docker certs are existing
      ansible.builtin.stat:
        path: "{{ certs_path }}"
      register: certs_dir

    - name: Fail if docker certs are not existing
      ansible.builtin.fail:
        msg: "Docker certificates are not existing in {{ certs_path }}."
      when: not certs_dir.stat.exists

    - name: Change docker daemon to use certs
      ansible.builtin.lineinfile:
        path: /lib/systemd/system/docker.service
        line: >
          ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
          -H tcp://{{ ansible_facts['default_ipv4']['address'] }}:2376 --tlsverify --tlscacert={{ certs_path }}/ca.pem
          --tlscert={{ certs_path }}/server-cert.pem --tlskey={{ certs_path }}/server-key.pem
        regexp: '^ExecStart='
        state: present

    - name: Reload systemd daemon
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Restart docker daemon
      ansible.builtin.systemd_service:
        name: docker
        state: restarted
        enabled: true
