---
- name: Docker Certs
  hosts: "{{ my_hosts | d([]) }}"
  become: true
  gather_facts: true

  vars:
    docker_tls_directory: /root/docker-certs
    docker_tls_key_type: RSA

    docker_tls_ca_cn: Docker Root CA
    docker_tls_ca_crt_file: docker_root_ca.crt.pem
    docker_tls_ca_key_file: docker_root_ca.key.pem

    docker_tls_certificate_cn: your-domain.tld
    docker_tls_certificate_crt_file: "{{ docker_tls_certificate_cn }}.crt.pem"
    docker_tls_certificate_key_file: "{{ docker_tls_certificate_cn }}.key.pem"
    docker_tls_certificate_validity_days: 3650

  tasks:
    - name: Ensure docker TLS directory
      ansible.builtin.file:
        path: "{{ docker_tls_directory }}"
        mode: '0710'
        owner: root
        group: root
        state: directory

    - name: Generate CA private key
      community.crypto.openssl_privatekey:
        path: "{{ docker_tls_directory }}/{{ docker_tls_ca_key_file }}"
        mode: '0640'
        owner: root
        group: root
        type: "{{ docker_tls_key_type }}"

    - name: Generate CA CSR
      community.crypto.openssl_csr_pipe:
        privatekey_path: "{{ docker_tls_directory }}/{{ docker_tls_ca_key_file }}"
        common_name: "{{ docker_tls_ca_cn }}"
        use_common_name_for_san: false
        basic_constraints:
          - CA:TRUE
        basic_constraints_critical: true
        key_usage:
          - keyCertSign
        key_usage_critical: true
      register: docker_tls_ca_csr
      changed_when: false
      check_mode: false

    - name: Generate CA certificate
      community.crypto.x509_certificate:
        path: "{{ docker_tls_directory }}/{{ docker_tls_ca_crt_file }}"
        mode: '0644'
        owner: root
        group: root
        csr_content: "{{ docker_tls_ca_csr['csr'] }}"
        privatekey_path: "{{ docker_tls_directory }}/{{ docker_tls_ca_key_file }}"
        provider: selfsigned

    - name: Generate client certificate's private key
      community.crypto.openssl_privatekey:
        path: "{{ docker_tls_directory }}/{{ docker_tls_certificate_key_file }}"
        mode: '0640'
        owner: root
        group: root
        type: "{{ docker_tls_key_type }}"

    - name: Generate client certificate's CSR
      community.crypto.openssl_csr_pipe:
        privatekey_path: "{{ docker_tls_directory }}/{{ docker_tls_certificate_key_file }}"
        subject_alt_name:
          - "DNS:{{ docker_tls_certificate_cn }}"
          - "IP:{{ ansible_facts['default_ipv4']['address'] | d(false) or omit }}"
      register: docker_tls_certificate_csr
      changed_when: false
      check_mode: false

    - name: Generate client certificate
      community.crypto.x509_certificate:
        path: "{{ docker_tls_directory }}/{{ docker_tls_certificate_crt_file }}"
        mode: '0644'
        owner: root
        group: root
        csr_content: "{{ docker_tls_certificate_csr['csr'] }}"
        privatekey_path: "{{ docker_tls_directory }}/{{ docker_tls_certificate_key_file }}"
        provider: ownca
        ownca_path: "{{ docker_tls_directory }}/{{ docker_tls_ca_crt_file }}"
        ownca_privatekey_path: "{{ docker_tls_directory }}/{{ docker_tls_ca_key_file }}"
        ownca_not_after: "+{{ docker_tls_certificate_validity_days }}d"
        ownca_not_before: '+0s'
